#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
echo "build script executed! Setting env here does not work... use rhc instead"
echo $OPENSHIFT_LOG_DIR
echo $RAILS_ENV
export RAILS_ENV=development
#export MY_OPENSHIFT_MONGODB_DB_CONNECTIONSTRING=$OPENSHIFT_MONGODB_DB_URL$OPENSHIFT_APP_NAME
#export MY_OPENSHIFT_MONGODB_DB_CONNECTIONSTRING=$OPENSHIFT_MONGODB_DB_HOST:$OPENSHIFT_MONGODB_DB_PORT
echo $RAILS_ENV
echo $OPENSHIFT_MONGODB_DB_URL$OPENSHIFT_APP_NAME > ~/.env/user_vars/MY_OPENSHIFT_MONGODB_DB_CONNECTIONSTRING
echo $OPENSHIFT_MONGODB_DB_HOST":"$OPENSHIFT_MONGODB_DB_PORT > ~/.env/user_vars/MY_OPENSHIFT_MONGODB_DB_HOSTPORT